# Site settings
title: Port Crane Fire Company

# email: contact@portcranefire.com
email: fire@kaymic.com

paginate: 10
paginate_path: "/news/page:num"

description: >
  Welcome to the new Port Crane Fire website

baseurl: ""
# baseurl: "/portcranefire"
url: "http://portcranefire.com"

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
